spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_ex?useSSL=false&serverTimezone=Asia/Seoul
    username: jpa_user
    password: jpa_user
    driver-class-name: com.mysql.cj.jdbc.Driver


